name: Update Quiz Manifests

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Make script executable
      run: chmod +x scripts/update-manifests.py
        
    - name: Update all quiz manifests
      run: |
        pwd
        ls -la
        ls -la wwwroot/quizzes/
        ls -la wwwroot/quizzes/lie-quiz/
        python3 scripts/update-manifests.py
        echo "After running script:"
        cat wwwroot/quizzes/lie-quiz/manifest.json
        echo "All manifests after update:"
        cat wwwroot/quizzes/sort-quiz/manifest.json
        cat wwwroot/quizzes/year-quiz/manifest.json
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add wwwroot/quizzes/*/manifest.json
        git status
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update quiz manifests"
          git push
        fi 